module.exports = {
  version: '0.1',
  language: 'en',
  minWordLength: 4,
  words: ['commitlint', 'stylelintrc', 'stylelintignore'],
  ignorePaths: [
    '**/*.svg',
    '**/*.sh',
    '**/*.conf',
    '**/*.png',
    '**/*.json',
    '**/*.lock',
    '**/*.ttf',
    '**/*.otf',
    '**/*.woff',
    '**/*.ogg',
    '**/*.yml',
    '**/*.yaml',
    'packages/**/*',
    'README.md',
    '.gitignore',
    '.prettierrc',
    '.prettierignore',
    '.eslintrc.js',
    '.eslintignore',
    '.stylelintrc.js',
    '.stylelintignore',
  ],
};
